### ISSUE TITLE
Suggestion: Integrating OpenModularTurrets into this mod

### ISSUE THREAD

**Issue by LokeYourC3PH** [offbeat-stuff/Zombie-Apocalypse#3]
Hey there! I was curious if, you'd be willing and open to the idea of integrating (or separately maintaining) OpenModularTurrets, since it would be a fine addition and expansion to this mod! If you're curious, here you go: https://github.com/OpenModularTurretsTeam/OpenModularTurrets

Good work so far, and I hope we can get some defence against the Zombie Hordes later :)

**Comment by offbeat-stuff** [comment]
well I was hoping that this mod was going to be purely server side.
Besides I dont have a computer rn, will not have one for months.
I develop this mod on my phone and sometimes borrow a computer. So cant really much else on other projects.

**Comment by offbeat-stuff** [comment]
Also I have tried this mod and the zombies so far are very easy to deal with.

Visit `Join at 193.123.71.216:8123
MC java 1.19.4, cracked users can join too`

this is Simply optimized smp server and well we have dealt with zombie hordes very easily.

You will see how well gaurded the spawn area is.
