### ISSUE TITLE
[Suggestion] Add a setting to stop spawning in bright light levels

### ISSUE THREAD

**Issue by Thelaststandn** [offbeat-stuff/Zombie-Apocalypse#5]
Currently the mod seems to disregard light levels when spawning zombies completely, I was able to spawn zombies on a platform that had nothing but torches on it.
Playing the mod with a friend, and this is really putting a wrench in playing. We stand in a well-lit room, and at the other end zombies spawn right in front of our eyes.
A setting that would stop spawns when in x light level and above would be amazing.

**Comment by offbeat-stuff** [comment]
Oh that will be easy.
Thanks for the suggestion.
